### ISSUE TITLE
Device provisioning from C8Y to Objenious LNS fails

### ISSUE THREAD

**Issue by phcrb** [SoftwareAG/cumulocity-lora#36]
Hello,
When I create a new device in C8Y using Objenious connector, the device is not created in C8Y nor in Objenious

The following message is found in the objenious connector:
https://lora-sandbox.dev.iot.greenflex.com/apps/administration/index.html#/applications/242/logs

2021-06-10 10:36:30.323  INFO 14 --- [http-nio-80-exec-10] lora.ns.objenious.ObjeniousConnector     : Response code from GET https://api.objenious.com/v1/devices/lora:0018b20000001447: 404
2021-06-10 10:36:30.323 ERROR 14 --- [http-nio-80-exec-10] lora.ns.objenious.ObjeniousConnector     : Error message from Objenious: 
2021-06-10 10:36:30.323 ERROR 14 --- [http-nio-80-exec-10] lora.ns.objenious.ObjeniousConnector     : Request was: Request{method=GET, url=https://api.objenious.com/v1/devices/lora:0018b20000001447, tags={class retrofit2.Invocation=lora.ns.objenious.rest.ObjeniousService.getDevice() [0018b20000001447]}}
2021-06-10 10:36:30.475  INFO 14 --- [http-nio-80-exec-10] lora.ns.objenious.ObjeniousConnector     : Response code from POST https://api.objenious.com/v1/devices: 403
2021-06-10 10:36:30.475 ERROR 14 --- [http-nio-80-exec-10] lora.ns.objenious.ObjeniousConnector     : Error message from Objenious: 
2021-06-10 10:36:30.475 ERROR 14 --- [http-nio-80-exec-10] lora.ns.objenious.ObjeniousConnector     : Request was: Request{method=POST, url=https://api.objenious.com/v1/devices, tags={class retrofit2.Invocation=lora.ns.objenious.rest.ObjeniousService.createDevice() [class DeviceCreate {
    label: lora-field-20
    deveui: 0018b20000001447
    appeui: 0018b24441524632
    appkey: c150015dc9cca58720db07cfbf9d7ee8
    groupId: 4
    profileId: 1
    lat: null
    lng: null
    properties: null
}]}}
2021-06-10 10:36:30.475 ERROR 14 --- [http-nio-80-exec-10] lora.ns.objenious.ObjeniousConnector     : {"code":"FORBIDDEN","message":"Service forbidden"}
2021-06-10 10:36:30.482  INFO 14 --- [http-nio-80-exec-10] lora.common.C8YUtils                     : External ID 0018b20000001447 with type LoRa devEUI not found

**Comment by phcrb** [comment]
creating the device from cumulocity:
![image](https://user-images.githubusercontent.com/84912886/124887822-d2a52b00-dfd5-11eb-9911-63d341ced06d.png)

I get this errors in the objenious µs logs:

2021-07-08 08:18:43.290  INFO 15 --- [http-nio-80-exec-4] lora.ns.objenious.ObjeniousConnector     : Response code from GET https://api.objenious.com/v1/devices/lora:70b3d5e75e0066d0: 404
2021-07-08 08:18:43.290 ERROR 15 --- [http-nio-80-exec-4] lora.ns.objenious.ObjeniousConnector     : Error message from Objenious: 
2021-07-08 08:18:43.290 ERROR 15 --- [http-nio-80-exec-4] lora.ns.objenious.ObjeniousConnector     : Request was: Request{method=GET, url=https://api.objenious.com/v1/devices/lora:70b3d5e75e0066d0, tags={class retrofit2.Invocation=lora.ns.objenious.rest.ObjeniousService.getDevice() [70b3d5e75e0066d0]}}
2021-07-08 08:18:43.427  INFO 15 --- [taskScheduler-12] lora.ns.LNSIntegrationService            : Getting pending operations on tenant t2244816
2021-07-08 08:18:43.496  INFO 15 --- [http-nio-80-exec-4] lora.ns.objenious.ObjeniousConnector     : Response code from GET https://api.objenious.com/v1/profiles: 200
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "deprecated" (class lora.ns.objenious.rest.Profile), not marked as ignorable (5 known properties: "icon", "link", "id", "icon_name", "name"])
 at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 1, column: 61] (through reference chain: java.util.ArrayList[0]->lora.ns.objenious.rest.Profile["deprecated"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:855)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1212)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1604)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1582)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:299)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:156)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:291)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:250)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2079)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1485)
	at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:32)
	at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:23)
	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:225)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:188)
	at lora.ns.objenious.ObjeniousConnector.provisionDevice(ObjeniousConnector.java:190)
	at lora.ns.LNSIntegrationService.provisionDevice(LNSIntegrationService.java:231)
	at lora.rest.LNSRestController.provisionDevice(LNSRestController.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.cumulocity.microservice.security.token.CumulocityOAuthMicroserviceFilter.doFilter(CumulocityOAuthMicroserviceFilter.java:89)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:126)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:118)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at com.cumulocity.microservice.security.filter.PostAuthenticateServletFilter$1.run(PostAuthenticateServletFilter.java:43)
	at com.cumulocity.microservice.context.ContextServiceImpl$CallableRunnableWrapper.call(ContextServiceImpl.java:119)
	at com.cumulocity.microservice.context.ContextServiceImpl$CallableRunnableWrapper.call(ContextServiceImpl.java:109)
	at com.cumulocity.microservice.context.ContextServiceImpl.callWithinContext(ContextServiceImpl.java:78)
	at com.cumulocity.microservice.context.ContextServiceImpl.runWithinContext(ContextServiceImpl.java:66)
	at com.cumulocity.microservice.context.ContextServiceImpl$4.run(ContextServiceImpl.java:129)
	at com.cumulocity.microservice.security.filter.PostAuthenticateServletFilter.doFilterInternal(PostAuthenticateServletFilter.java:78)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:158)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:204)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at com.cumulocity.microservice.security.filter.PreAuthenticateServletFilter$1.run(PreAuthenticateServletFilter.java:42)
	at com.cumulocity.microservice.context.ContextServiceImpl$CallableRunnableWrapper.call(ContextServiceImpl.java:119)
	at com.cumulocity.microservice.context.ContextServiceImpl$CallableRunnableWrapper.call(ContextServiceImpl.java:109)
	at com.cumulocity.microservice.context.ContextServiceImpl.callWithinContext(ContextServiceImpl.java:78)
	at com.cumulocity.microservice.context.ContextServiceImpl.runWithinContext(ContextServiceImpl.java:66)
	at com.cumulocity.microservice.context.ContextServiceImpl$4.run(ContextServiceImpl.java:129)
	at com.cumulocity.microservice.security.filter.PreAuthenticateServletFilter.doFilterInternal(PreAuthenticateServletFilter.java:75)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at com.cumulocity.microservice.security.token.CumulocityOAuthMicroserviceFilter.doFilter(CumulocityOAuthMicroserviceFilter.java:89)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:92)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:77)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:109)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:747)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
2021-07-08 08:18:43.504  INFO 15 --- [http-nio-80-exec-4] lora.common.C8YUtils                     : External ID 70b3d5e75e0066d0 with type LoRa devEUI not found

**Comment by cpoder** [comment]
Added @JsonIgnoreProperties(ignoreUnknown = true) annotation on Profile class so this error should not appear anymore.
This "deprecated" field is not documented in Objenious, so I'm ignoring it.
The issue should be fixed now.

**Comment by haraldmeyer** [comment]
Has been fixed.
